### ISSUE TITLE
Кнопочки в партнерах на моб версии не агонь. может чет придумаем покрасивее?

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/tqg-lp#13]
![default](https://cloud.githubusercontent.com/assets/11279857/7231692/90c07ce4-e77f-11e4-8af7-fb09d08b058f.png)

**Comment by Wilvarin** [comment]
хорошая заставка

2015-04-20 17:07 GMT+03:00 Nikolay_R <notifications@github.com>:

**Comment by nikolayr1** [comment]
![firefox_wallpaper](https://cloud.githubusercontent.com/assets/11279857/7231790/52b3ee76-e780-11e4-8b52-528507cc1605.png)
не благодари. а теперь за дело

**Comment by AndruAlex** [comment]
я думаю она там вообще не нужна 
сейчас сенсерные телефоны поэтому её убрать нужно

**Comment by dadakax** [comment]
Просто без них непонятно, что эслайдер и его можно листать

**Comment by AndruAlex** [comment]
ну не знаю

**Comment by nikolayr1** [comment]
кнопочки мы выбрали и сделаем.
