### ISSUE TITLE
В мобильной опере все плохо

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/tqg-lp#15]
![](https://pp.vk.me/c624019/v624019526/28239/hbNXTs88m0k.jpg)

![](https://pp.vk.me/c624019/v624019526/28242/PIGliGwHUBI.jpg)
не подключаются шрифты и вообще стили походу не такие

и скругление не работает
12:28:38	
и кончено прогружается текстура за логотипом

**Comment by nikolayr1** [comment]
мы ничего не сможем поделать если опера - это конченый браузер
