### ISSUE TITLE
Ховеры (изменение состояния при наведении на объект)

### ISSUE THREAD

**Issue by dadakax** [TopQualityGuys/tqg-lp#19]
Ховеры на кнопке меню в моб версии, на кнопках в моб версии блока знания, и на кнопке прокрутки, на стрелочках в партнерах (и в моб версии и в большой)
Плюс еще курсор поинтер на стрелочках

**Comment by nikolayr1** [comment]
ховер в мобильной версии не нужен, ведь сделать наведение невозможно

**Comment by dadakax** [comment]
а ну да, согласна

**Comment by dadakax** [comment]
тогда только на стрелочках в большом слайдере в партнерах и на кнопке прокрутки

**Comment by nikolayr1** [comment]
хавера для кнопке прокрутки вверх не будет - это решение дизайнера

**Comment by nikolayr1** [comment]
ховеры добавлены на все что только есть на сайте)
