### ISSUE TITLE
Тонкий шрифт. Голубой цвет.

### ISSUE THREAD

**Issue by successus** [TopQualityGuys/tqg-lp#2]
@olleskiv, мне кажется, что шрифт в меню и других местах слишком тонкий,

этот голубой цвет  в меню усиливает эту незаметность.  
Мне кажется, что синий здесь не вписывается.

**Comment by nikolayr1** [comment]
на сайте не должно быть голубого цвета, но почему-то в некоторых браузерах цвета некоторых ссылок навигации становятся синими. это очень странно...
