### ISSUE TITLE
партнеры, моб. версия

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/tqg-lp#23]
стрелочки не забудьте поменять

**Comment by nikolayr1** [comment]
![partnery_strelka](https://cloud.githubusercontent.com/assets/11279857/7253329/8ba9c312-e844-11e4-8b9a-6b4231f45d50.png)
эти стрелочки нужно поставить

**Comment by nikolayr1** [comment]
стрелочки поменял
