### ISSUE TITLE
Форма контактов

### ISSUE THREAD

**Issue by successus** [TopQualityGuys/tqg-lp#28]
Сделать так, чтобы она работала.

То есть, При нажатии на кнопку "отправить",
javascript собирает все данные формы
проверяет их на валидность(корректность), 
Если есть ошибки, выводить красным сообщение об ошибке,
Если нет - отправляет данные на php файл, который уже отправляет нам на email

**Comment by dadakax** [comment]
у нас имейла нет

**Comment by dadakax** [comment]
Может создать типа корпоративную почту на нашем домене? Через gmail можно вроде

**Comment by successus** [comment]
А зачем тогда писали TQG@gmail.com ?
Что за херня? Зачем бутафория? 
Форма не рабочая, емейл не настоящий. Как клиенты вообще должны с нами контактировать?

**Comment by dumbik** [comment]
done
