### ISSUE TITLE
Горизонтальная прокрутка

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/tqg-lp#29]
На нашем сайте некоторые блоки имеют ширину >320px. это нужно устранить.
![image](https://cloud.githubusercontent.com/assets/11279857/7430608/34909db2-f01e-11e4-858c-428cb69b0b6f.png)
например этот блок
![image](https://cloud.githubusercontent.com/assets/11279857/7430628/62f7bd34-f01e-11e4-9508-91ec03776572.png)

**Comment by dumbik** [comment]
до 320 я этот блок сузить не могу, ибо не помещаются текста. это нужно дизайн менять. а это уже к Оле скорее. Все равно никто не сидит в инете с телефонами, где ширина экрана 320 px - это слишком мало.
