### ISSUE TITLE
Зеленые полосы в why-us

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/tqg-lp#30]
зеленые полосы слазят вниз при языке en и ua
![image](https://cloud.githubusercontent.com/assets/11279857/7430654/c2e9affe-f01e-11e4-8363-708c9e17d114.png)
![image](https://cloud.githubusercontent.com/assets/11279857/7430657/cb81c6b0-f01e-11e4-82a0-a727c1a7de6f.png)
на ru все работает
![image](https://cloud.githubusercontent.com/assets/11279857/7430661/daf5f602-f01e-11e4-8645-d8091368951f.png)

**Comment by dadakax** [comment]
done
