### ISSUE TITLE
Стиль блока связи

### ISSUE THREAD

**Issue by nikolayr1** [TopQualityGuys/tqg-lp#31]
вид блока contact-us нужно поменять в согласии с требованиями дизайнера. фоновая images/bg.jpg
![k3d8dvmyf-i](https://cloud.githubusercontent.com/assets/11279857/7430711/57a577f4-f01f-11e4-9353-f1bf9e6056d8.jpg)

**Comment by dumbik** [comment]
Оля согласилась оставить так, как есть. оно смотрится норм. так что я закрываю.
