### ISSUE TITLE
Партнеры, средний размер

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/tqg-lp#33]
![image](https://cloud.githubusercontent.com/assets/11739563/7441021/2a19362c-f0dd-11e4-8237-bae9e6f35c91.png)
когда окно экрана шириной более 560 пикселей, загружать сразу два лого с расстоянием в 20 пикселей друг от друга

**Comment by dumbik** [comment]
стрелочки точно уезжают в задницу какую-то
