### ISSUE TITLE
блок знания 

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/tqg-lp#35]
![image](https://cloud.githubusercontent.com/assets/11739563/7441071/23cb942a-f0df-11e4-9b59-76ea222a380b.png)
В полной версии поменять шрифт категорий на PantonBlackItalicCaps, а пунктов категорий на  PantonLightCaps.

![image](https://cloud.githubusercontent.com/assets/11739563/7441080/af8be74e-f0df-11e4-9d51-7b8df2ba476d.png)
В мобильной версии поставить высоту белых прямоугольников по 40 пикселей каждый

**Comment by dumbik** [comment]
шрифты поменял, высота по 40 пикселей как была, так и осталась.
