### ISSUE TITLE
блок наша команда

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/tqg-lp#36]
![image](https://cloud.githubusercontent.com/assets/11739563/7441101/234f9670-f0e1-11e4-9d3e-232b044a3a5a.png)

Если остается две фотографии внизу, размещать их таким образом, как на фотографии. Расстояние между кружочками 90 пикселей

![image](https://cloud.githubusercontent.com/assets/11739563/7441106/5498e22c-f0e1-11e4-881d-43810c2fffe7.png)

Поменять Дашу и Олю местами, чтобы лица смотрели внутрь сайта

**Comment by dumbik** [comment]
местами то я поменял, а вот с позиционированием не получилось - при добавлении отступов последние 2 нижние блока начинают дергаться при наведении на них. хз в чем проблема
