### ISSUE TITLE
Первый блок 

### ISSUE THREAD

**Issue by olleskiv** [TopQualityGuys/tqg-lp#37]
![image](https://cloud.githubusercontent.com/assets/11739563/7441121/b9a25742-f0e2-11e4-81f0-5d13c7740476.png)

Поменять в надписи "команда отличных веб-разработчиков" шрифт на PantonLightCaps.

Увеличить размер надписи "узнать больше" до 12 пикселей. Если буквы все равно будут сливаться, тоже поменять шрифт на PantonLightCaps.

**Comment by olleskiv** [comment]
если возможно (не будет вылазить за плашку) увеличить размер шрифта  "команда отличных веб-разработчиков" до 18 пикс

**Comment by nikolayr1** [comment]
"узнать больше" 14 пикс(было 12px). "команда отличных веб-разработчиков"  шрифт PantonLightCaps 18px
