### ISSUE TITLE
От тестировщика услышал!

### ISSUE THREAD

**Issue by AndruAlex** [TopQualityGuys/tqg-lp#39]
стоять ховери на картинки назв того, що ви робите (сайт-візитка, лендінг пейдж, форуми, ...) і на назвах технологій в "знанія" + в розділі "с намі работают" коли наводиш на стрілочку "далі" не змнюється форма курсора + перелік не круговий (можна ітльки в одну або іншу сторону. по колу назви не ходять)
повторюсь, але це тільки моя думка, може це все так і задумувалось)

**Comment by dumbik** [comment]
слайдер теперь уже работает по кругу
