### ISSUE TITLE
Блок "Что мы делаем"

### ISSUE THREAD

**Issue by VoronaMV** [TopQualityGuys/tqg-lp#48]
- [x] Поменять название блока
- [x] Изменить мелкий вылетающий текст каждой карточки на форму для заказа с полями:
- Краткий комментарий услуги
- Кнопка "заказать", которая кидает на форму обратной связи
- [x] Поменять последовательность блоков в таком порядке:
1. Интернет магазин;
2. Лендинг пейдж;
3. Сайт-каталог;
4. Сайт-визитка;
5. Рекламная кампания;
6. Поисковая оптимизация;
7. Веб приложение;
8. Прилож. на андройд;

**Comment by VoronaMV** [comment]
Варианты названия блока:
- Закажите современный сервис, который будет полностью соответствовать вашим желаниям
- Мы разработаем современное решение для Вашего бизнеса
- Закажите современное решение для Вашего бизнеса

**Comment by nikolayr1** [comment]
Закажите современное решение для Вашего бизнеса - делаем это
