### ISSUE TITLE
Блок "Наши преимущества"

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/tqg-lp#59]
Нужно переделать этоот блок. Верстка едет так, что просто стыдно такое иметь на сайте как по мне
![image](https://cloud.githubusercontent.com/assets/11014944/15625835/367e98b0-24be-11e6-9d99-adf4c4a801c7.png)

**Comment by dumbik** [comment]
Если задачи закрыта, при чем 4 дня назад, то почему у нас на tqg.com.ua такая хрень?
![image](https://cloud.githubusercontent.com/assets/11014944/15741199/493bc0de-28c1-11e6-802e-0df020fad5d1.png)

**Comment by F0oocuS** [comment]
@dumbik який браузер і яке розширення. попробуй почистити кеш в мене все ок 
![image](https://cloud.githubusercontent.com/assets/14852050/15820765/2b6eb12a-2bf4-11e6-8e6c-7fa116353993.png)

**Comment by dumbik** [comment]
уже норм
