### ISSUE TITLE
Блок "Наша команда"

### ISSUE THREAD

**Issue by dumbik** [TopQualityGuys/tqg-lp#61]
Блок такой: 
![image](https://cloud.githubusercontent.com/assets/11014944/15741263/8bc75378-28c1-11e6-9ebd-4fdbd5eb38c5.png)

А при хувере на Олю такой:
![image](https://cloud.githubusercontent.com/assets/11014944/15741277/9a994ee2-28c1-11e6-93cb-32d94c273e89.png)

**Comment by F0oocuS** [comment]
перевірив нічого не пригає 
![image](https://cloud.githubusercontent.com/assets/14852050/15820703/ca656e32-2bf3-11e6-8691-4688e2915893.png)

**Comment by dumbik** [comment]
уже норм
